version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  test-bdd:
    executor:
      name: node/default
      tag: '18.17'   # ✅ Node.js 18 (LTS, Playwright supported)
    steps:
      - checkout

      # Install Node dependencies
      - node/install-packages:
          pkg-manager: npm

      # Install Playwright browsers + Linux deps
      - run:
          name: Install Playwright Browsers
          command: npx playwright install --with-deps

      # Run BDD tests
      - run:
          name: Run BDD Tests
          command: npm run test:bdd

workflows:
  sample:
    jobs:
      - test-bdd
