# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  sample:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
          test-command: "npm run test:bdd"
